<a href="https://colab.research.google.com/github/MeenakshiRajpurohit/ISE-201-Math-Foundations-for-Decision-Data-Sciences/blob/main/Linear_systems_as_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:


import numpy as np
import matplotlib.pyplot as plt
#from utils import plot_lines # Removed since the utils module is not available

In [19]:
A = np.array ([
    [-1, 3],
    [3, 2]
], dtype= np.dtype(float))

b = np.array([7, 1], dtype= np.dtype(float))

print('Matrix A:')
print(A)
print('Matrix b:')
print(b)



Matrix A:
[[-1.  3.]
 [ 3.  2.]]
Matrix b:
[7. 1.]


In [20]:
print(f'Shape of A: {A.shape}')
print(f'Shape of b: {b.shape}')

Shape of A: (2, 2)
Shape of b: (2,)


In [21]:
x = np.linalg.solve(A,b)

print(f'Sloution {x}')

Sloution [-1.  2.]


In [22]:
d = np.linalg.det(A)

print(f'Determinant of A: {d:.2f}')

Determinant of A: -11.00


In [23]:
A_system = np.hstack((A, b.reshape((2, 1))))

print(A_system)

[[-1.  3.  7.]
 [ 3.  2.  1.]]


In [24]:
print(A_system[1])

[3. 2. 1.]


In [25]:
plot_lines(A_system) # Removed since the plot_lines function is not defined

NameError: name 'plot_lines' is not defined