<a href="https://colab.research.google.com/github/MeenakshiRajpurohit/ISE-201-Math-Foundations-for-Decision-Data-Sciences/blob/main/matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from numpy.linalg import matrix_power
a = np.array([[1, 2],[3,4]])
print(matrix_power(a,2))
print(matrix_power(a,10))

[[ 7 10]
 [15 22]]
[[ 4783807  6972050]
 [10458075 15241882]]


In [4]:
import numpy as np
i = np.identity(2)
print(i)

[[1. 0.]
 [0. 1.]]


In [6]:
print(np.zeros((4,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
a = np.arange(16).reshape((4,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [11]:
print(np.triu(a))

[[ 0  1  2  3]
 [ 0  5  6  7]
 [ 0  0 10 11]
 [ 0  0  0 15]]


In [14]:
print(np.tril(a))

[[ 0  0  0  0]
 [ 4  5  0  0]
 [ 8  9 10  0]
 [12 13 14 15]]


In [17]:
b = np.array([[1,2], [3,4]])
print(b)
np.linalg.det(b)

[[1 2]
 [3 4]]


np.float64(-2.0000000000000004)

In [20]:
matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
v_rotated = np.rot90(matrix)

print('Original', matrix)
print('rotated', v_rotated)

Original [[1 2 3]
 [4 5 6]
 [7 8 9]]
rotated [[3 6 9]
 [2 5 8]
 [1 4 7]]


In [24]:
c = np.matrix([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(c)
print(c.transpose())
print(c.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [28]:
d = np.array([[1, 2, 1], [2, 1, 2], [1, 2, 2]])
print(d)

d1 = np.linalg.inv(d)
print(d1)

print(d @ d1)

print(d1 @ d)

[[1 2 1]
 [2 1 2]
 [1 2 2]]
[[ 0.66666667  0.66666667 -1.        ]
 [ 0.66666667 -0.33333333  0.        ]
 [-1.          0.          1.        ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
